# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06200cc26ad1c3f88310a3acb6668441d811d98af24030a19661c862a3473e11cda247aba79ee039cc56c009a9519baf1eb03858a2ae9555a0f33976cffea535

test:
  secret_key_base: a6bd9b65073989171936fa575ee57eb0dbf3a5d2cdc611eda40483dc02aa6e565c31b85957e89629bf65a835ff1333a2c5bd9be932cd2fac198cff63acc94796

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
